# This is a basic workflow to help you get started with Actions

name: 2nd Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  create:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Zip Chromium
        uses: thedoctor0/zip-release@main
     
        id: chrome-zip
        with: 
          type: zip
          filename: chromium.zip
          directory: chrome
          exclusions: '*.git* /*node_modules/* .editorconfig'  
          
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: v0.3.0
          release_name: Release v0.3.0
          draft: true
          body: |
            Chromium: "https://github.com/webKythe/wSource/releases/v0.3.0"
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.create-new-release.outputs.upload_url }}
           asset_path: chrome/chromium.zip
           asset_name: chromium_latest.zip 
           asset_content_type: application/zip     
          
          
