name: 3rd Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  create:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Zip Chromium
        uses: thedoctor0/zip-release@main
        id: chrome-zip
        with: 
          type: zip
          filename: chromium.zip
          directory: chrome
          exclusions: '*.git* /*node_modules/* .editorconfig'  
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v3.0.0"
          release: "v3.0.0"
          artifacts: "chrome/chromium.zip"
          body: |
            This is how the world see
          bodyFile: "README.md"     
          draft: true
          name: " New v3.0.0"
          generateReleaseNotes: true
          makeLatest: true
          
