# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  create:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3 
    
        
      - name: Zip Chromium
        uses: thedoctor0/zip-release@main
        with: 
            filename: chromium.zip
            directory: test2 
            exclusions: '*.git*  *.gitignore* /*individualdownload/*'
            
      - name: Schedule Release
        uses: "marvinpinto/action-automatic-releases@latest"
        id: create-release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1.1"
          draft: true
          files: |
            chrome
