---
name: MergeFolder
on: 
  
  pull_request:
    types:
      - closed

  workflow_dispatch:    
  
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           token: ${{ secrets.GH_TOKEN }}
      
      - name: Initiate Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Merge Json    
        run: python merge.py
      - name: Commit & Push
        uses: actions-x/commit@v6
        with:
          email: 100699190+webVerts@users.noreply.github.com
          name: GitHub Actions
          branch: main
