---
name: MergeFolder
on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types:
      - closed

  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Initiate Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Merge Json    
        run: python merge.py
      - name: Commit & Push
        
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "100699190+webVerts@users.noreply.github.com"
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
