name: MergeFolder

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python merge.py  
      
      - name: Commit & Push
        uses: actions-x/commit@v6
        with:
           email: 100699190+webVerts@users.noreply.github.com
           name: GitHub Actions
           branch: main
     
